In [1]:
import pandas as pd
import numpy as np

**Removing Duplicates**

**Transforming Data Using a Function or Mapping**

**Replacing values**

**Renaming indexes**

**Discriazation and bining**

**Detecting and filtering outliers**

# REMOVING DUPLICATES

**DataFrame.duplicated()**


**DataFrame.drop_duplicates()**

In [40]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,'k2': [1, 1, 2, 3, 3, 4, 4]})

In [41]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [42]:
 data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [44]:
data['v1'] = range(7)

In [45]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [46]:
 data.drop_duplicates(['k1', 'k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

# Transforming Data Using a Function or Mapping

**Series.map()**

In [15]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                   'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [16]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [27]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [23]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [25]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

# Replacing Values

**DataFrame.replace()**

In [47]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [29]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [37]:
 data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [32]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [33]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

**Series.str.title()**: Convert strings in the Series/Index to titlecase.

**Series.str.lower()**: Converts all characters to lowercase.

**Series.str.upper()**: Converts all characters to uppercase.

**DataFrame.rename(mapper=dict-like or function, index=dict-like or function, columns=dict-like or function, axis=0/1, copy=True default, inplace=False default, level=None, errors='ignore')**

In [48]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])

In [57]:
data.index.map(str.upper)

Index(['INDIANA', 'COLORADO', 'NEW YORK'], dtype='object')

In [50]:
data.index = data.index.map(str.upper)

In [51]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [52]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [53]:
data.rename(index={'OHIO': 'INDIANA'},columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [63]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [64]:
 data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# Discretization and Binning


**pandas.cut(x =1-dimensional array , bins= int/sequence of scalars , right=bool/default True, labels=array or False, retbins=False, precision=The precision (decimal) at which to store and display the bins labels, include_lowest=False,duplicates='raise',ordered=True)**


**pandas.qcut(x=1d ndarray or Series, q=int or list, labels=array or False, retbins=False, precision=The precision (decimal) at which to store and display the bins labels** **(Quantile-based discretization function)**


In [3]:
ages = [20, 40, 25,91,37]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (35, 60], (18, 25], (60, 100], (35, 60]]
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [4]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [36, 61), [18, 26), [61, 100), [36, 61)]
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [5]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [6]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'MiddleAged', 'Youth', 'Senior', 'MiddleAged']
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [7]:
 data = np.random.rand(20)

In [8]:
pd.cut(data, 4, precision=2)

[(0.24, 0.48], (-0.00078, 0.24], (-0.00078, 0.24], (0.72, 0.97], (0.24, 0.48], ..., (0.72, 0.97], (0.72, 0.97], (0.24, 0.48], (-0.00078, 0.24], (0.24, 0.48]]
Length: 20
Categories (4, interval[float64]): [(-0.00078, 0.24] < (0.24, 0.48] < (0.48, 0.72] < (0.72, 0.97]]

In [10]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(-0.687, -0.0172], (0.661, 4.118], (-0.0172, 0.661], (0.661, 4.118], (-0.0172, 0.661], ..., (-0.0172, 0.661], (0.661, 4.118], (0.661, 4.118], (0.661, 4.118], (-3.738, -0.687]]
Length: 1000
Categories (4, interval[float64]): [(-3.738, -0.687] < (-0.687, -0.0172] < (-0.0172, 0.661] < (0.661, 4.118]]

In [11]:
pd.value_counts(cats)

(0.661, 4.118]       250
(-0.0172, 0.661]     250
(-0.687, -0.0172]    250
(-3.738, -0.687]     250
dtype: int64

In [12]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.273, -0.0172], (1.283, 4.118], (-0.0172, 1.283], (1.283, 4.118], (-0.0172, 1.283], ..., (-0.0172, 1.283], (1.283, 4.118], (-0.0172, 1.283], (1.283, 4.118], (-1.273, -0.0172]]
Length: 1000
Categories (4, interval[float64]): [(-3.738, -1.273] < (-1.273, -0.0172] < (-0.0172, 1.283] < (1.283, 4.118]]

# Detecting and Filtering Outliers

In [48]:
data = pd.DataFrame(np.random.randint(12,size= (6,2)))
data

0  1
0   0  1
1   5  3
2   3  1
3   2  6
4   2  9
5  10  6

In [49]:
data.describe()  

0         1
count   6.000000  6.000000
mean    3.666667  4.333333
std     3.502380  3.204164
min     0.000000  1.000000
25%     2.000000  1.500000
50%     2.500000  4.500000
75%     4.500000  6.000000
max    10.000000  9.000000

In [50]:
col = data[1]

In [51]:
col[np.abs(col) > 3]

3    6
4    9
5    6
Name: 1, dtype: int32

In [52]:
 data[(np.abs(data) > 3).any(1)]

0  1
1   5  3
3   2  6
4   2  9
5  10  6

In [53]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [54]:
data

0  1
0  0  1
1  3  3
2  3  1
3  2  3
4  2  3
5  3  3

In [55]:
data.describe()

0         1
count  6.000000  6.000000
mean   2.166667  2.333333
std    1.169045  1.032796
min    0.000000  1.000000
25%    2.000000  1.500000
50%    2.500000  3.000000
75%    3.000000  3.000000
max    3.000000  3.000000

# Permutation and Random Sampling

In [58]:
 df = pd.DataFrame(np.arange(20).reshape(5, 4))

In [60]:
sampler = np.random.permutation(5)

In [61]:
 sampler

array([3, 4, 0, 1, 2])

In [63]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

In [72]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15

To generate a sample with replacement, the fastest way is to use np.random.randint to
draw random integers:

In [65]:
bag = np.array([5, 7, -1, 6, 4])

In [66]:
sampler = np.random.randint(0, len(bag), size=10)

In [67]:
sampler

array([2, 0, 0, 0, 2, 4, 1, 1, 0, 4])

In [68]:
draws = bag.take(sampler)

In [69]:
draws

array([-1,  5,  5,  5, -1,  4,  7,  7,  5,  4])

# Computing Indicator/Dummy Variables


**pandas.get_dummies(data = array-like/Series/DataFrame, prefix=str/list of str/dict of str, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)**

In [98]:
 df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})

In [99]:
 pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [100]:
 dummies = pd.get_dummies(df['key'], prefix='key')

In [101]:
df_with_dummy = df[['data1']].join(dummies)

In [102]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [151]:
values = np.random.rand(10)

In [152]:
values

array([0.06677147, 0.5608676 , 0.28813697, 0.76112145, 0.88278137,
       0.63420529, 0.74536615, 0.18264415, 0.80341527, 0.47151162])

In [147]:
 bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [148]:
 pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           1           0           0
1           0           0           0           1           0
2           0           0           1           0           0
3           0           1           0           0           0
4           0           0           0           1           0
5           0           0           0           1           0
6           1           0           0           0           0
7           0           0           0           1           0
8           1           0           0           0           0
9           0           0           0           0           1