# INTRODUCTION TO DATA STRUCTURE



**SERIES**

A Series is a one-dimensional array-like object containing an array of data (of any
NumPy data type) and an associated array of data labels, called its index.

In [208]:
import pandas as pd
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

the **values** attribute returns the data contained in the DataFrame as a 2D
ndarray:

In [209]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

pandas**.Series**   (**data**=array-like, Iterable, dict, or scalar value, **index**=array-like or Index (1d))

In [203]:
obj = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [204]:
df.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [205]:
obj['a']

-5

In [206]:
obj[obj > 0]

d    4
b    7
c    3
dtype: int64

In [207]:
'b' in obj

True

In [31]:
#creating a Series from it by passing the dict:
dict={'Cristiano':36,'Messi':33,'Neymar':28,'Mbappe':22}

In [32]:
obj3=pd.Series(dict)
obj3

Cristiano    36
Messi        33
Neymar       28
Mbappe       22
dtype: int64

In [38]:
dict2={}
Country = ['Cristiano', 'Lewandowski', 'Neymar', 'Kimmich']
obj4 = pd.Series(dict, index=Country)
obj4

Cristiano      36.0
Lewandowski     NaN
Neymar         28.0
Kimmich         NaN
dtype: float64

In [39]:
 pd.isnull(obj4)

Cristiano      False
Lewandowski     True
Neymar         False
Kimmich         True
dtype: bool

# DataFrame


**.DataFrame(data=ndarray/dict/DataFrame, index=Index or array-like or list, columns=Index or array-like, dtype=None, copy=False)**

In [65]:
dict={'player':['Cristiano','Messi','Neymar','Mbappe'],'age':[36,33,28,22],'FifaBest':[5,6,0,0]}

In [66]:
frame=pd.DataFrame(dict)

In [67]:
frame

player  age  FifaBest
0  Cristiano   36         5
1      Messi   33         6
2     Neymar   28         0
3     Mbappe   22         0

In [68]:
pd.DataFrame(dict, columns=['FifaBest', 'player', 'age'])

FifaBest     player  age
0         5  Cristiano   36
1         6      Messi   33
2         0     Neymar   28
3         0     Mbappe   22

In [76]:
frame2 = pd.DataFrame(dict, columns=['FifaBest', 'player', 'age','Active'],index=['one', 'two', 'three','four'])

In [77]:
frame2
#if you pass a column that isn’t contained in data, it will appear with NA values in the result

FifaBest     player  age Active
one           5  Cristiano   36    NaN
two           6      Messi   33    NaN
three         0     Neymar   28    NaN
four          0     Mbappe   22    NaN

In [78]:
frame2['age']

one      36
two      33
three    28
four     22
Name: age, dtype: int64

In [82]:
frame2['Active'] = 'Yes'

In [83]:
frame2

FifaBest     player  age Active
one           5  Cristiano   36    Yes
two           6      Messi   33    Yes
three         0     Neymar   28    Yes
four          0     Mbappe   22    Yes

In [98]:
import numpy as np
frame2['Active'] = np.arange(4)

In [99]:
frame2

FifaBest     player  age  Active
one           5  Cristiano   36       0
two           6      Messi   33       1
three         0     Neymar   28       2
four          0     Mbappe   22       3

In [117]:
val = pd.Series([7, 10,7], index=['one','three', 'four'])

In [118]:
val

one       7
three    10
four      7
dtype: int64

In [119]:
frame2['active'] = val

In [120]:
frame2

FifaBest     player  age  Active  active  exist
one           5  Cristiano   36       0     7.0  False
two           6      Messi   33       1     NaN  False
three         0     Neymar   28       2    10.0  False
four          0     Mbappe   22       3     7.0  False

In [123]:
frame2['exist'] = frame2.active == 7.0

In [124]:
frame2

FifaBest     player  age  Active  active  exist
one           5  Cristiano   36       0     7.0   True
two           6      Messi   33       1     NaN  False
three         0     Neymar   28       2    10.0  False
four          0     Mbappe   22       3     7.0   True

In [125]:
 del frame2['exist']

In [126]:
frame2

FifaBest     player  age  Active  active
one           5  Cristiano   36       0     7.0
two           6      Messi   33       1     NaN
three         0     Neymar   28       2    10.0
four          0     Mbappe   22       3     7.0

In [174]:
pop = {'Cristiano': {2019: 31, 2009: 33,2002:2},'Messi': {2019: 33, 2009: 48, 2004: 1}}

In [175]:
frame3 = pd.DataFrame(pop)

In [179]:
frame3

Cristiano  Messi
2019       31.0   33.0
2009       33.0   48.0
2002        2.0    NaN
2004        NaN    1.0

In [191]:
fb = {'Cristiano': frame3['Cristiano'][:-1],'Messi': frame3['Messi'][:2]}

In [192]:
pd.DataFrame(fb)

Cristiano  Messi
2002        2.0    NaN
2009       33.0   48.0
2019       31.0   33.0

In [195]:
frame3.index.name = 'Year'; frame3.columns.name = 'Player'

In [196]:
frame3

Player  Cristiano  Messi
Year                    
2019         31.0   33.0
2009         33.0   48.0
2002          2.0    NaN
2004          NaN    1.0

Like Series, the values attribute returns the data contained in the DataFrame as a 2D
ndarray:

In [197]:
frame3.values

array([[31., 33.],
       [33., 48.],
       [ 2., nan],
       [nan,  1.]])

**INDEX OBJECTS**

In [223]:
obj =pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [224]:
index = obj.index

In [225]:
index

Index(['a', 'b', 'c'], dtype='object')

In [215]:
index[1:]

Index(['b', 'c'], dtype='object')

In [216]:
index = pd.Index(np.arange(3))

In [218]:
obj2 = pd.Series([1.5, -2.5, 0], index=index)

In [219]:
obj2.index is index

True

In [272]:
a=np.array([[1,5,9,3],[3,6,7,8]])
b=np.array([1,3,7,4])

In [273]:
np.append(a,b)

array([1, 5, 9, 3, 3, 6, 7, 8, 1, 3, 7, 4])

In [275]:
np.diff(b)

array([ 2,  4, -3])

In [276]:
np.intersect1d(a,b)

array([1, 3, 7])

In [278]:
np.delete(a,2)

array([1, 5, 3, 3, 6, 7, 8])

In [287]:
np.unique(a)

array([1, 3, 5, 6, 7, 8, 9])

# Essential Functionality

**.reindex**

In [289]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [290]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

**.reindex(labels=None, index=series, columns=series, axis=0/1, method=bfill/ffill/nearest, copy=True, level=None, fill_value=nan, limit=None, tolerance=None)**

In [291]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [292]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [293]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [295]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [296]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [316]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [317]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [321]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 1, 4])

In [307]:
obj3.reindex(range(6), method='ffill')

0      blue
1    purple
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [361]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])

In [362]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [364]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill')

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8