# LEARNING OBJECTIVES

**Dropping entries from an axis**

**Indexing, Selection, Filtering**

**Arithmetic Data Alignment**

**Operation Between DataFrame and series**

**Function Application and Mapping**

**Sorting and Ranking**


# Dropping entries from an axis

**.drop(labels=single label or list-like, axis=0/1, index=single label or list-like, columns=single label or list-like, level=None, inplace=False, errors='raise')**

In [1]:
import pandas as pd
import numpy as np 


obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [3]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [4]:
new_obj = obj.drop('b') #or(['b','d'])

In [5]:
new_obj

a    0.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [3]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [4]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [8]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data.drop(['two','one'], axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

# Indexing, selection, and filtering





**Series.loc(Access group of values using labels.)**

**DataFrame.iloc(Access group of rows and columns by integer position(s).)**

In [10]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [11]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [12]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [13]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [14]:
obj['b':'c'] = 5

In [15]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [7]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [8]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [19]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [21]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [22]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [23]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

# Arithmetic and data alignment

**.add**

In [24]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [25]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [26]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [27]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

**.DataFrame(data=ndarray/dict/DataFrame, index=Index or array-like or list, columns=Index or array-like, dtype=None, copy=False)**

In [11]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])

In [12]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [13]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [14]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [15]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [20]:
 df1.add(df2, fill_value=0) #nan values are nan in both sides

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [17]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [40]:
df1.reindex(columns=df2.columns, fill_value=0) #using columns bde of df2

b    d  e
Ohio      0.0  2.0  0
Texas     3.0  5.0  0
Colorado  6.0  8.0  0

# Operations between DataFrame and Series

**.sub(sequence, Series, axis='columns', level=int or label, fill_value=0)**

In [41]:
arr = np.arange(12.).reshape((3, 4))

In [42]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [43]:
arr[0]

array([0., 1., 2., 3.])

In [44]:
 arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [2]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [3]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [6]:
series = frame.iloc[2]

In [7]:
series

b    6.0
d    7.0
e    8.0
Name: Texas, dtype: float64

In [61]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [62]:
series2

b    0
e    1
f    2
dtype: int64

In [73]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [74]:
series3 = frame['d']

In [75]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [95]:
frame.sub(series3, axis=0) # series3 subtracted by frame

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function application and mapping


**DataFrame.apply(func, axis=0/1)** returns a Series or DataFrame

In [108]:
frame = pd.DataFrame(np.random.randint(10, size=(4,4)), columns=list('bdef'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [109]:
frame

b  d  e  f
Utah    6  3  3  3
Ohio    4  1  5  4
Texas   5  2  5  2
Oregon  7  2  3  5

In [110]:
f = lambda x: x.max() - x.min()

In [111]:
frame.apply(f)

b    3
d    2
e    2
f    3
dtype: int64

In [112]:
frame.apply(f, axis=1)

Utah      3
Ohio      4
Texas     3
Oregon    5
dtype: int64

In [116]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b  d  e  f
min  4  1  3  2
max  7  3  5  5

In [117]:
format = lambda x: '%.2f' % x

In [118]:
frame.applymap(format) #DataFrame.applymap(func, na_action=None) #returns Transformed DataFrame.

b     d     e     f
Utah    6.00  3.00  3.00  3.00
Ohio    4.00  1.00  5.00  4.00
Texas   5.00  2.00  5.00  2.00
Oregon  7.00  2.00  3.00  5.00

In [123]:
frame['d'].map(format)

Utah      3.00
Ohio      1.00
Texas     2.00
Oregon    2.00
Name: d, dtype: object

# Sorting and ranking

**DataFrame.sort_index(axis=0/1, level=None, ascending=True/False, inplace=False, kind='quicksort', na_position='last', sort_remaining=True, ignore_index=False, key=None)**


**DataFrame.sort_values(by='str' , axis=0/1, ascending=True/False, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)**

**DataFrame.rank(axis=0/1, method={‘average’, ‘min’, ‘max’, ‘first’, ‘dense’}, numeric_only=None, na_option='keep', ascending=True, pct=False)**



In [124]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [125]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [140]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index=['three', 'one'],columns=['d', 'a', 'b', 'c'])

In [141]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [146]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [147]:
obj = pd.Series([4, 7, -3, 2])

In [149]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [151]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [153]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [155]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [160]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [192]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [193]:
obj.rank() #series ranking,if both the numbers are same,they share the number by +0.5 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

* 'average' Default: assign the average rank to each entry in the equal group.
* 'min' Use the minimum rank for the whole group.
* 'max' Use the maximum rank for the whole group.
* 'first' Assign ranks in the order the values appear in the data.

In [198]:
obj.rank(ascending=True, method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [196]:
 frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})

In [197]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [199]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Axis indexes with duplicate values

In [204]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [207]:
df.loc['b']

0         1         2
b -0.916036 -0.388001 -0.097550
b  0.258465  0.257266  0.540377